@host= http://localhost:3333/


POST {{host}}auth/signin
Content-Type: application/json

{}

###
POST {{host}}auth/signup
Content-Type: application/json

{
    "email":"test@email.com",
    "password":"1234"
}

###