#@host= http://localhost:3333/


POST {{baseURL}}auth/signin
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "1234"
}

###
POST {{baseURL}}auth/signup
Content-Type: application/json

{
    "email":"test@email.com",
    "password":"1234"
}

###
GET {{baseURL}}users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJpYXQiOjE2OTAyMzMyNDUsImV4cCI6MTY5MDIzNDE0NX0.u9KHWzxA7EzVofsoWuvxFe6OKUcXv7IHs83TM44z678

###
