#@host= http://localhost:3333/


POST {{baseURL}}auth/signin
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "1234"
}

###
POST {{baseURL}}auth/signup
Content-Type: application/json

{
    "email":"test@email.com",
    "password":"1234"
}

###